[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "postgresql_15"]

[phases.install]
cmds = [
  "cd bot && python3 -m venv venv",
  "cd bot && source venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"
]

[start]
cmd = "cd bot && source venv/bin/activate && python3 api.py"
